set_property SRC_FILE_INFO {cfile:{C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/btnL.xdc} rfile:../../../../../btnL.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/btnR.xdc} rfile:../../../../../btnR.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/clock.xdc} rfile:../../../../../clock.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/led.xdc} rfile:../../../../../led.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/sseg.xdc} rfile:../../../../../sseg.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/switches.xdc} rfile:../../../../../switches.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/btnU.xdc} rfile:../../../../../btnU.xdc id:7} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/btnD.xdc} rfile:../../../../../btnD.xdc id:8} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/btnC.xdc} rfile:../../../../../btnC.xdc id:9} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports btnL]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports btnR]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property src_info {type:XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property src_info {type:XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property src_info {type:XDC file:4 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property src_info {type:XDC file:4 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property src_info {type:XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property src_info {type:XDC file:4 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property src_info {type:XDC file:4 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property src_info {type:XDC file:4 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property src_info {type:XDC file:4 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property src_info {type:XDC file:4 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property src_info {type:XDC file:4 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property src_info {type:XDC file:4 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property src_info {type:XDC file:4 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property src_info {type:XDC file:4 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property src_info {type:XDC file:4 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property src_info {type:XDC file:4 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
set_property src_info {type:XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property src_info {type:XDC file:5 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property src_info {type:XDC file:5 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property src_info {type:XDC file:5 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property src_info {type:XDC file:5 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property src_info {type:XDC file:5 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property src_info {type:XDC file:5 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property src_info {type:XDC file:5 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property src_info {type:XDC file:5 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property src_info {type:XDC file:5 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property src_info {type:XDC file:5 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property src_info {type:XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property src_info {type:XDC file:6 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property src_info {type:XDC file:6 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property src_info {type:XDC file:6 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property src_info {type:XDC file:6 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property src_info {type:XDC file:6 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property src_info {type:XDC file:6 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property src_info {type:XDC file:6 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property src_info {type:XDC file:6 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
set_property src_info {type:XDC file:6 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
set_property src_info {type:XDC file:6 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
set_property src_info {type:XDC file:6 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
set_property src_info {type:XDC file:6 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
set_property src_info {type:XDC file:6 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
set_property src_info {type:XDC file:6 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
set_property src_info {type:XDC file:6 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]
set_property src_info {type:XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports btnU]
set_property src_info {type:XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports btnD]
set_property src_info {type:XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports btnC]
