# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/Lab11_guess.runs/synth_1/.Xil/Vivado-9916-DESKTOP-5LV72DU/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      {C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/Lab11_guess.srcs/sources_1/new/counter.sv}
      {C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/Lab11_guess.srcs/sources_1/new/debounce.sv}
      {C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/Lab11_guess.srcs/sources_1/new/guess_FSM.sv}
      {C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/Lab11_guess.srcs/sources_1/new/mux_2.sv}
      {C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/Lab11_guess.srcs/sources_1/new/guessing_game.sv}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList {{C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/Lab11_guess.runs/synth_1/.Xil/Vivado-9916-DESKTOP-5LV72DU/realtime/guessing_game_synth.xdc}}
    rt::sdcChecksum
    set rt::top guessing_game
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/Lab11_guess.cache/wt}
    rt::set_parameter enableSplitFlowPath "C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/Lab11_guess.runs/synth_1/.Xil/Vivado-9916-DESKTOP-5LV72DU/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
