webtalk_init -webtalk_dir H:/ELC2137/DL202010_meyers/Lab05 Vivado/Lab05_project/Lab05_project.sim/sim_2/behav/xsim/xsim.dir/fulladder_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 13 15:54:37 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "176094205_174126154_210553245_322" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f6530f12-52d4-4cbc-8151-22dc93077ffe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1848f03819fe42beb30c5f128b505651" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "80 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6612_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1855974002 -regid "176094205_174126154_210553245_322" -xml H:/ELC2137/DL202010_meyers/Lab05 Vivado/Lab05_project/Lab05_project.sim/sim_2/behav/xsim/xsim.dir/fulladder_test_behav/webtalk/usage_statistics_ext_xsim.xml -html H:/ELC2137/DL202010_meyers/Lab05 Vivado/Lab05_project/Lab05_project.sim/sim_2/behav/xsim/xsim.dir/fulladder_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm H:/ELC2137/DL202010_meyers/Lab05 Vivado/Lab05_project/Lab05_project.sim/sim_2/behav/xsim/xsim.dir/fulladder_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
