webtalk_init -webtalk_dir C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/Lab11_guess.sim/sim_2/behav/xsim/xsim.dir/guess_FSM_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 23 14:01:30 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c2a425ea-236f-4621-a1e4-5061b88e9c05" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f31178ec071e4d89b487a8e39aa914b4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5560_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3395327612 -regid "" -xml C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/Lab11_guess.sim/sim_2/behav/xsim/xsim.dir/guess_FSM_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/Lab11_guess.sim/sim_2/behav/xsim/xsim.dir/guess_FSM_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/maken/Documents/ELC Lab 2137/DL202010_meyers/Lab11/Lab11_guess/Lab11_guess.sim/sim_2/behav/xsim/xsim.dir/guess_FSM_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
